-- begin MAILING_MAILING
alter table MAILING_MAILING add constraint FK_MAILING_MAILING_ON_MAILING_TARGET_SCRIPT foreign key (MAILING_TARGET_SCRIPT_ID) references MAILING_GROOVY_SCRIPT(ID)^
alter table MAILING_MAILING add constraint FK_MAILING_MAILING_ON_OBJECT_FILTER_SCRIPT foreign key (OBJECT_FILTER_SCRIPT_ID) references MAILING_GROOVY_SCRIPT(ID)^
alter table MAILING_MAILING add constraint FK_MAILING_MAILING_ON_FINAL_CHECK_SCRIPT foreign key (FINAL_CHECK_SCRIPT_ID) references MAILING_GROOVY_SCRIPT(ID)^
alter table MAILING_MAILING add constraint FK_MAILING_MAILING_ON_FINAL_DECORATION_SCRIPT foreign key (FINAL_DECORATION_SCRIPT_ID) references MAILING_GROOVY_SCRIPT(ID)^
create index IDX_MAILING_MAILING_ON_MAILING_TARGET_SCRIPT on MAILING_MAILING (MAILING_TARGET_SCRIPT_ID)^
create index IDX_MAILING_MAILING_ON_OBJECT_FILTER_SCRIPT on MAILING_MAILING (OBJECT_FILTER_SCRIPT_ID)^
create index IDX_MAILING_MAILING_ON_FINAL_CHECK_SCRIPT on MAILING_MAILING (FINAL_CHECK_SCRIPT_ID)^
create index IDX_MAILING_MAILING_ON_FINAL_DECORATION_SCRIPT on MAILING_MAILING (FINAL_DECORATION_SCRIPT_ID)^
-- end MAILING_MAILING
-- begin MAILING_NOTIFICATION
alter table MAILING_NOTIFICATION add constraint FK_MAILING_NOTIFICATION_ON_TARGET foreign key (TARGET_ID) references SEC_USER(ID)^
alter table MAILING_NOTIFICATION add constraint FK_MAILING_NOTIFICATION_ON_MAILING foreign key (MAILING_ID) references MAILING_MAILING(ID)^
create index IDX_MAILING_NOTIFICATION_ON_TARGET on MAILING_NOTIFICATION (TARGET_ID)^
create index IDX_MAILING_NOTIFICATION_ON_MAILING on MAILING_NOTIFICATION (MAILING_ID)^
-- end MAILING_NOTIFICATION
-- begin MAILING_MAILING_IDENTIFIER
create unique index IDX_MAILING_IDENTIFIER_UK_OBJECT_ID on MAILING_MAILING_IDENTIFIER (OBJECT_ID) where DELETE_TS is null ^
-- end MAILING_MAILING_IDENTIFIER
